# default configuration
baseURL = "https://decandido.dev"
languageCode = "en-us"
summaryLength = "10"
theme = "kross"
title = "Development | De Candido"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
URL = "plugins/slick/slick.css"

[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"

[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 2

[[menu.hidden]]
URL = "portfolio"
name = "Portfolio"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# theme color
theme_color = "#f50057"
# contact info
phone = "+39 335 781 2244"
email = "hello@decandido.dev"
address = "South Tyrol, Italy"
# meta description
author = "Gabriele De Candido"
description = "Web Designer, Web Developer, Software Engineer from Bolzano, South Tyrol (Italy)"
# google analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 - Gabriele De Candido"


# contact
[params.contact]
enable = true
form_action = "https://formspree.io/mvoaldpz" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.svg" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://www.linkedin.com/in/de-candido/"
icon = "ti-linkedin"

[[params.social]]
URL = "https://www.instagram.com/gab__ph/"
icon = "ti-instagram"

[[params.social]]
URL = "https://github.com/lelebus/"
icon = "ti-github"
